#设备标识
machine_id: ''

#皇冠网站地址
crown_url: 'https://mos011.com'

#队列名配置
queues:
  surebet_check: 'v3:surebet_check'
  ready_check_after: 'v3:ready_check_after'
  final_check: 'v3:final_check'
  crown_matches_data: 'v3:crown_matches_data'
  send_promoted: 'v3:send_promoted'
  send_promoted_channel2: 'v3:send_promoted_channel2'

surebet:
  #surebet接口调用凭证
  token: ''
  #获取到数据后需要抛到的下一个队列
  next_queues:
    - 'surebet_check'
    - 'v3:surebet_check'

#采集到皇冠比赛数据后要抛到的队列
crown_matches_data_queues:
  - 'crown_matches_data'
  - 'v3:crown_matches_data'

#数据库配置
db:
  host: ''
  port: 5432
  username: ''
  password: ''
  database: ''
  #连接池配置
  pool:
    min: 0
    max: 5

#Redis配置
redis:
  #连接配置
  connection:
    host: ''
    port: 6379
    password: ''
  #连接池配置
  pool:
    min: 0
    max: 5

#rabbitmq配置
rabbitmq:
  hostname: ''
  port: 5672
  username: ''
  password: ''
  heartbeat: 25

#Luffa机器人配置
luffa:
  uid: ''
  secret: ''
  #提醒消息的通知目标
  notification:
    - type: 1
      uid: ''
      atList:
        - name: ''
          did: ''
